### ISSUE TITLE
Modify link to button and make it available on toolbar

### ISSUE THREAD

**Issue by sag1** [cosmocode/dokuwiki-plugin-diagrams#12]
Hello,

Thanks for this great plugin !

The present link `Create diagram` is not so visible. I searched for a while to find out. Could you please modify it to button and make it available on the toolbar to ease user's experience ?

**Comment by annda** [comment]
Diagrams are more like other media files, so the media manager is the proper place to create them. As with other media, you can use the media button in the toolbar to open the popup and create a diagram there. 

Also thanks for #21 I am closing both issues via #22
