### ISSUE TITLE
ACL Problems

### ISSUE THREAD

**Issue by mtkirchner** [cosmocode/dokuwiki-plugin-diagrams#17]
The documentation says "Edit buttons are available in two places:
    in the fullscreen media manager in the View tab, which is displayed when an image is selected
    on a wiki page with an embedded diagram (only if the user has upload permissions for the given diagram file)."

While the first is ok I find the second to be true only when logged in as admin.

In addition I am not able to create a diagram as user with the media manager popup. No error is produced, only the file is not created.

ACL are set on the namespace. I do not know how to set a permission on a mediafile, but I guess namespace is what is meant.

On the other hand, I am allowed to change/upload the diagram file via the full screen media manager.

I would guess my ACL is corrupted, but as both ways should yield identical results, there also might be something wrong with the ACL checks in the code.

**Comment by splitbrain** [comment]
Without an exact description on how your ACLs are set up and what namespaces and pages are involved, it's hard to reproduce the problem or do any kind of diagnose.

**Comment by mtkirchner** [comment]
Agreed. (I had the hope the difference between full screen media manager and popup might help.) 
NS ist playground

The ACL is long.

Relevant lines are 
playground:*	@user	16
playground:*	@gast	16 

What else could I do to help?

**Comment by mtkirchner** [comment]
Can I give more information on the problem?

**Comment by mtkirchner** [comment]
Is the testsystem OK? Any input needed?

**Comment by splitbrain** [comment]
I think this should be enough to reproduce the problem, thank you. I can't say when we will have time to look into it.

**Comment by mtkirchner** [comment]
Doing some debugging: 

It seems that ACL for diagrams is checked against the full id with leading colon while ACLs in the acl.auth.php file are defined without leading colon.

So auth_aclcheck_cb would try to match ":playground:file.svg" against ACL-Rule "playground:*" and give no result.

If in the example above I add another line with colon at the start.


    @user	1
    @ALL	0
    playground:* @user	8
    :playground:* @user	8

It works.

Removing the leading colon from every $image string in editableDiagrams:action.php in the plugin "diagrams", I do get the Edit-button and can edit the svg, but the new file is not uploaded and replaced. So I guess the wrong check is done somewhere else still.

Removing the leading colon in auth_aclcheck_cb:auth.php from $id (and implicitly $ns) before matching solves the issue. But beeing the heart of security of Dokuwiki, please double-check, some things are still strange.

function auth_aclcheck_cb($data) {
    $id     =& $data['id'];
    $id=preg_replace('/^\:/','',$id);
    $user   =& $data['user'];
    $groups =& $data['groups'];

**Comment by sven** [comment]
Thanks @mtkirchner for analyzing this. It helped me workarounding the issue by simply disabling the check as the wiki is only used in a small environment. After removing the ACL check I encountered a second problem when the `savedir` is set to an absolute path which doesn't play well with prepending `DOKU_INC`.

Here are the two workarounds:

### editableDiagrams - auth_quickaclcheck doesn't work correctly

Remove `auth_quickaclcheck($image) >= AUTH_UPLOAD` from:

    foreach ($images as $image) {
        if (auth_quickaclcheck($image) >= AUTH_UPLOAD && $this->isDiagram($image)) {
            $editable[] = $image;
        }   
    }

Result:

    foreach ($images as $image) {
        if ($this->isDiagram($image)) {
            $editable[] = $image;
        }   
    }

### isDiagram - savedir contains absolute path

Remove `DOKU_INC .` from:

    $file = DOKU_INC .
        $conf['savedir'] .
        DIRECTORY_SEPARATOR .
        'media' .
        DIRECTORY_SEPARATOR .
        preg_replace(['/:/'], [DIRECTORY_SEPARATOR], $image);

Result:

    $file = $conf['savedir'] .
        DIRECTORY_SEPARATOR .
        'media' .
        DIRECTORY_SEPARATOR .
        preg_replace(['/:/'], [DIRECTORY_SEPARATOR], $image);

**Comment by annda** [comment]
@sven Thanks for reporting. The `savedir` problem is unrelated to this issue, but was fixed in #19 together with the ACL check.

**Comment by sven** [comment]
@annda Thank you for the information.
