### ISSUE TITLE
Non admin users cannot save their diagrams

### ISSUE THREAD

**Issue by alainb1** [cosmocode/dokuwiki-plugin-diagrams#18]
I recently installed the diagrams plugin on my dokuwiki website. I tested it myself and everything works fine for me (as admin). However, regular users of the website cannot save their diagrams.

More precisely, after saving their diagram, regular users return to the media manager window where there is no .svg file saved. It seems there is a permission issue for them to save the file. However, I checked the ACL and the regular users should have all access (they can edit, modify and save files outside of the diagrams extension).

Is this a known issue ? Could there be a reason for such behaviour ? I do not have the impression to have missed anything during the installation...

Thank you !

**Comment by annda** [comment]
Fixed in #20
