### ISSUE TITLE
Google Fonts Loading Problem using SVG/Diagram

### ISSUE THREAD

**Issue by sz10101** [cosmocode/dokuwiki-plugin-diagrams#23]
Copied from: https://github.com/splitbrain/dokuwiki/issues/3709#issue-1299831350

I'm testing RC2 (Igor) and comparing functionality to Hogfather on IIS (both on Win 10)  

Trying to load an SVG image created using the **diagrams** plugin (I am using the most current (April '22) version on both hogfather and igor.

Using the **_default docuwiki template_** for both Igor and Hogfather.

Added the following items to \conf\meta.html:

```
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&family=Roboto&family=Roboto+Flex:opsz@8..144&family=Source+Code+Pro&display=swap" rel="stylesheet">
```

Trying to render an SVG file which references the external Google font "Architects Daughter".

Because the problem occurs on Igor and NOT on Hogfather, I'm recording an issue here.

More information:

fetch.php attempts to retrieve the SVG document and the following error is thrown in the "Developer tools" Issues log:

Refused to load the font 'data:application/x-font-ttf;charset=utf-8;base64,AAEAAAAMAIAAAwBAT1MvMoWwV7IAAGWAAAAAYGNtYXDPBugkAABl4AAAARxnYXNwAAAAEAAAkvgAAAAIZ2x5Zv2v7C0AAADMAABb/GhlYWQC0dksAABfqAAAADZoaGVhCEMEFgAAZVwAAAAkaG10eN2yH1kAAF/gAAAFfGxvY2GKxKMcAABc6AAAAsBtYXhwAa4AzAAAXMgAAAAgbmFtZUarZSoAAGcEAAAlEHBvc3QANIw5AACMFAAABuNwcmVwaAaMhQAAZvwAAAAHAAIAFv/5AHwDhQAKABMAADcyFhUGBwYiJicmEwYQByM0NxI1PyoTCyUGDhUFC1sGD0MIDkMQCSgIAQgKGQNhGv2rLWebAS1pAAIANgHqANcC+wALABcAABM3JzQ3FxUXDgEjIic3JzQ3FxUXDgEjIpIBASQREAMZBSRcAQEkEBEEGAUkAlIcKVMREMciAw...V4DFRjb21tYWFjY2VudAx0Y29tbWFhY2NlbnQGVGNhcm9uBFRiYXIEdGJhcgZVdGlsZGUGdXRpbGRlB1VtYWNyb24HdW1hY3JvbgZVYnJldmUGdWJyZXZlBVVyaW5nBXVyaW5nDVVodW5nYXJ1bWxhdXQNdWh1bmdhcnVtbGF1dAdVb2dvbmVrB3VvZ29uZWsLV2NpcmN1bWZsZXgLd2NpcmN1bWZsZXgLWWNpcmN1bWZsZXgLeWNpcmN1bWZsZXgGWmFjdXRlBnphY3V0ZQpaZG90YWNjZW50Cnpkb3RhY2NlbnQHQUVhY3V0ZQdhZWFjdXRlC09zbGFzaGFjdXRlC29zbGFzaGFjdXRlDFNjb21tYWFjY2VudAxzY29tbWFhY2NlbnQGV2dyYXZlBndncmF2ZQZXYWN1dGUGd2FjdXRlCVdkaWVyZXNpcwl3ZGllcmVzaXMGWWdyYXZlBnlncmF2ZQRFdXJvC2NvbW1hYWNjZW50AAABAAH//wAP' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

I've set the CORS setting to be * in the configuration.  With or without the "*", the same error appears.

The issue that I'm seeing is that the FONT does not render properly within the SVG image but the SVG vectors and shading **does** render properly.  

This is an example SVG which demonstrates the problem:

![test](https://user-images.githubusercontent.com/76440945/178132112-c7206d26-68cc-4cba-86c8-b288879ead0a.svg)

Steps to reproduce:

1. Position the attached test file into the \data\media directory as 'test.svg'
2. Access the image through the media manager and view it using 'edit diagram' function.

The image should appear properly as 
![image](https://user-images.githubusercontent.com/76440945/178132160-f1558b40-2a22-4d16-9c05-aab3853ede4b.png)

Attempt to insert that image on a test page '{{ :test.svg |}}' and the following will appear:
![image](https://user-images.githubusercontent.com/76440945/178132195-08ba1ccc-e3aa-44f1-b283-a44a6bedc70f.png)

Thank you

From Andreas:

https://github.com/splitbrain/dokuwiki/issues/3709#issuecomment-1179666209

**Comment by sz10101** [comment]
**Temporary Workaround**

I would generate the pull request myself but because I'm of insufficient depth in understanding the internals of Dokuwiki, as a temporary workaround in "Igor" - I've changed \lib\exe\fetch.exe's declaration of array parameter 'csp' passed to "FETCH_MEDIA_STATUS" to permit 'self' and data;.

```
       'csp' => [
            'sandbox' => '',
            'default-src' => "'none'",
            'style-src' => "'unsafe-inline'",
            'font-src' => "'self' data: ",  // added this line
            'media-src' => "'self'",
            'object-src' => "'self'",
            'form-action' => "'none'",
            'frame-ancestors' => "'self'",
        ],
```

**Comment by splitbrain** [comment]
The plugins sets its own CSP headers now.
