### ISSUE TITLE
Graphics are not shown

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [cosmocode/dokuwiki-plugin-diagrams#24]
Hi,

if the diagram becomes too complex, some graphic elements embedded are only partially displayed.

When one opens the diagram editor, all elements are shown. And if one exports the graphic from within the editor as an SVG file, this file also is correct. So inside the SVG file, nothing is lost.

So what can I do?

Best regards
Juergen

**Comment by j0hu** [comment]
Hello, 

I have the same problem - are there a workaround or a solution for this in the meanwhile?

my network plan into the diagram.io editor (image section):

![grafik](https://user-images.githubusercontent.com/43872769/191023674-1e2bd093-35ae-4341-ad86-9d4a224f43bc.png)

and so it looks like into dokuwiki:

![grafik](https://user-images.githubusercontent.com/43872769/191023542-2332c8a1-81a1-43f2-9dd4-f85c60903047.png)


Greetings, Jochen

**Comment by splitbrain** [comment]
Can you upload an affected SVG here?

**Comment by Juergen-aus-Zuendorf** [comment]
![it_landschaft](https://user-images.githubusercontent.com/1800472/193824464-91624d08-3c1f-4943-a015-ff913d0e950f.svg)

**Comment by Juergen-aus-Zuendorf** [comment]
I'll send it to you by mail
