### ISSUE TITLE
SVG are not displayed, due to nocache parameter

### ISSUE THREAD

**Issue by bitmind** [cosmocode/dokuwiki-plugin-diagrams#35]
Issue: after adding a diagram to a page, the diagram is not rendered, only the Edit diagram button appear.

- Browser inspector indicates a 404 on the svg url: /dokuwiki/lib/exe/fetch.php/mypage/mydiagram.svg&cache=nocache
- Removing "&cache=nocache" laed to a valid url.
- I temporarily tweaked   lib/plugins/diagrams/syntax.php   in order to change the link, but I guess this issue should be further investigated

**Comment by splitbrain** [comment]
I think this no longer applies to the most recent release. Feel free to reopen if it still happens
