### ISSUE TITLE
Can't save diagrams to a dokuwiki page

### ISSUE THREAD

**Issue by swiftanna** [cosmocode/dokuwiki-plugin-diagrams#44]
Hello! I'm running a self-hosted diagrams.net (draw.io) webapp with apache tomcat + apache2 server on a local network. In my dokuwiki, everything works fine, but I can't save diagrams created via "diagrams" plugin. There is no save button on the right side of diagrams editor, only "share" button. "Diagrams" webapp proposes me to save my diagram to a cloud service or to my computer, but I can't save it to my dokuwiki page for some reason :( Am I missing something?

My setup:
- Operating system: Ubuntu 22.04.2 LTS
- Apache 2 server with DokuWiki installed.
- Tomcat server that runs as www-data user with draw.io (diagrams) webapp installed on it.

Apache 2 is configured to run only in local network (ip range). Cross domain requests allowed in Apache 2 (tomcat serves apps via a different port than Apache 2).

DokuWiki is available at a local ip address. Draw.io webapp is available at the same ip address, but with a :8080 added at the end.

Maybe I have to set permissions somewhere else?

![save-dialog01](https://github.com/cosmocode/dokuwiki-plugin-diagrams/assets/140731966/4a5c4dca-082e-4116-b9fe-e69a9ccb3d75)
![save-dialog02](https://github.com/cosmocode/dokuwiki-plugin-diagrams/assets/140731966/71284d4a-6e59-42ed-9ce0-29a642a5d48d)

**Comment by binauchhier** [comment]
Can you please post the URL for diagrams.net, that is set in konfiguration-> diagrams.

**Comment by swiftanna** [comment]
> Can you please post the URL for diagrams.net, that is set in configuration-> diagrams.

The url set in the **configuration -> diagrams** is _http://192.168.0.195:8080/draw/_
The editor works but can save only to the desktop, not the wiki. The option to save diagrams to a wiki page simply does not appear.

**Comment by swiftanna** [comment]
> This is the wrong URL. It should be: http://192.168.0.195:8080/draw/?embed=1&proto=json&spin=1&svg-warning=0

Many thanks! The "Save" button have finally appeared, but when I try to save a diagram, the page says that it cannot be saved. Dev console shows a 403 error. What permissions I have possibly forgotten to set?
![saving-failed](https://github.com/cosmocode/dokuwiki-plugin-diagrams/assets/140731966/0d6fcd87-297b-4f39-99de-61a6912191d7)
![saving-failed-console](https://github.com/cosmocode/dokuwiki-plugin-diagrams/assets/140731966/f84d1c00-d006-4117-830e-862c259cf2b1)

**Comment by binauchhier** [comment]
Well, at this point, im sorry, but I cannot help any more. My suggestions would be: clear browser-cache, check permissions of Dokuwiki-paths in apache. Maybe the port :8080 is causing the Problem? Try it without it.

**Comment by swiftanna** [comment]
I've found the reason why it didn't work. I didn't setup a connector between Apache2 and Tomcat properly. Instead of mod_jk (which didn't work), I decided to use mod_proxy, mod_proxy_http and mod_proxy_html (you need to enable all these mods via system console as described [here](https://www.digitalocean.com/community/tutorials/how-to-use-apache-as-a-reverse-proxy-with-mod_proxy-on-ubuntu-16-04)). The tutorial on a more precise config for those mods can be found [here](https://cwiki.apache.org/confluence/display/HTTPD/TomcatReverseProxy) and [here](https://cwiki.apache.org/confluence/display/HTTPD/TomcatModProxyHTML).

With all the preparations done, I've changed **configuration -> diagrams** URL setting to _http://192.168.0.195/apps/draw/?embed=1&proto=json&spin=1&svg-warning=0_

It works now! 🌞
