### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by Nils98Ar** [cosmocode/dokuwiki-plugin-diagrams#51]
Sometimes the umlauts on the page are broken after saving a diagram. Any idea?

Did not occur without the diagrams plugin.

**Comment by Nils98Ar** [comment]
This seems to happen when editing the diagram from within the ProseMirror editor.

**Comment by splitbrain** [comment]
Please describe in detail how to reproduce the problem.

**Comment by Nils98Ar** [comment]
In the beginning the files encoding is utf-8:
```
file -bi start.txt
text/plain; charset=utf-8
```

If I click the edit diagram button on the page (not in the editor) and save the diagram everything works as expected and if I open the ProseMirror editor and save the page without editing the diagram everything works as expected as well and the encoding is still utf-8:
```
file -bi start.txt
text/plain; charset=utf-8
```

But if I 
1. Open the ProseMirror editor via `Edit this page`
2. Click the diagram and then `Diagramm editieren`
3. Save the diagram

Then when clicking `OK` in the "Diagrammeigenschaften" popup the diagram that was previously rendered as image within the editor changes to an icon with diagram name next to it:
![image](https://github.com/cosmocode/dokuwiki-plugin-diagrams/assets/48221746/02bd8e6c-99cd-4995-aa62-7b62df518876)

When clicking `Speichern` in the editor all umlauts on the page are broken, for example "Überblick" changes to "Ãberblick" and the encoding if unknown/mixed:
```
file -bi start.txt
text/plain; charset=unknown-8bit
```

**Comment by annda** [comment]
I can reproduce the encoding errors in **ProseMirror** editor only when the **embedded** diagram itself contains text with special characters, e.g. German Umlauts. @Nils98Ar can you confirm that editing embedded diagrams on pages containing Umlauts works fine as long the diagrams themselves have no special characters?

**Comment by Nils98Ar** [comment]
@annda Thank you!
