### ISSUE TITLE
Impossible to save diagram if multiple image from outside

### ISSUE THREAD

**Issue by e471wo** [cosmocode/dokuwiki-plugin-diagrams#57]
### Issue Description

Hi, 
Found a bug here (I guess) wich is bizarre.  When I copy paste multiple images (png, for example) into diagram, impossible to save it but only when two or more image are inside.(Seems a link on image do not support multiple).

For exemple, here two images
![sun](https://github.com/cosmocode/dokuwiki-plugin-diagrams/assets/64007061/a0c2831a-3312-4a10-a614-d902f854f2ac)
![earth](https://github.com/cosmocode/dokuwiki-plugin-diagrams/assets/64007061/df351d7f-cc05-407c-b596-341f0628ea1f)

1) Create a diagram in dokuwiki.
2) Copy paste one image. 
3) copy paste the second image.
4) save the document

Expected... the document is save with the both image inside.
What I have : "impossible to save document " message. 

You can do that on any diagram. 
To save, just delete one of the both image. (the saving only work with 1 image).

thanks

**Comment by splitbrain** [comment]
I used drag'n'drop to add the two images above to a diagram. The result saved fine:

![screenshot-cosmocode wiki-2024 07 29-08_07_01](https://github.com/user-attachments/assets/2445461d-c3f6-460b-87a7-c05f70fff548)

Next I downloaded both images, loaded them in Gimp, copied them from there and pasted them in the same diagram. This worked fine as well:

![screenshot-cosmocode wiki-2024 07 29-08_11_06](https://github.com/user-attachments/assets/134c8296-5d7e-463a-bedf-5a691bf509dc)

There was a considerable delay when saving the second time. Not sure if that's related to your issue or a fluke on my side. In any case, I cannot reproduce the issue.
