### ISSUE TITLE
Option for own diagrams.net instance

### ISSUE THREAD

**Issue by githubkoma** [cosmocode/dokuwiki-plugin-diagrams#6]
Dear Creators,
many thanks for this great plugin!
how much effort would it be to implement the possibility to reference an own diagrams.net instance?
like to "https://diagrams.mycompany.org" or whatever..

best regards

**Comment by splitbrain** [comment]
If you're asking for a quote, best send an email to dokuwiki@cosmocode.de

**Comment by githubkoma** [comment]
No, but i could **try to** put an basic Entry in the DokuWiki options menu and open a pull request, if thats also fine?
First have to check out if it currently fits my time schedule ;/

**Comment by annda** [comment]
merged #7
